#!/bin/sh
set -eu


ui_dir=usdx_dl/web/ui
dist_dir=usdx_dl/web/dist


# ANSI codes
ansi_reset="\033[0m"
ansi_bold="\033[1m"
ansi_red="\033[31m"
ansi_green="\033[32m"
ansi_yellow="\033[33m"
ansi_blue="\033[34m"
ansi_magenta="\033[35m"
ansi_cyan="\033[36m"


# helper functions
pnpm() {
  pushd "$ui_dir" >/dev/null
  command pnpm "$@"
  popd >/dev/null
}

step() {
  echo -e "${ansi_bold}${ansi_magenta}[pre-commit] $1${ansi_reset}"
}

fatal() {
  echo -e "${ansi_bold}${ansi_red}[pre-commit] ERROR: $1${ansi_reset}"
  exit 1
}


# venv
if [ -d ".venv" ]; then
  step "Using existing .venv"
else
  step "Creating new .venv"
  uv venv
fi
. .venv/bin/activate
uv pip install --editable ".[dev]"


# node modules
step "Installing Node.js dependencies"
pnpm install


# format
step "Formatting Python"
ruff check --select I --fix --exit-non-zero-on-fix  # sort imports
ruff format --exit-non-zero-on-format
step "Formatting JS/TS"
pnpm run format


# lint
step "Linting Python"
ruff check --fix --exit-non-zero-on-fix
step "Linting JS/TS"
pnpm run lint


# build
step "Building UI"
mkdir -p "$dist_dir"
dist_hash_before=$(find "$dist_dir" -type f | sort | xargs sha256sum)
pnpm run build
dist_hash_after=$(find "$dist_dir" -type f | sort | xargs sha256sum)
if [ "$dist_hash_before" != "$dist_hash_after" ]; then
  echo ">>>>>>>"
  echo "$dist_hash_before"
  echo "======="
  echo "$dist_hash_after"
  echo "<<<<<<<"
  fatal "UI build artifacts have changed. Please commit the updated files."
fi


# test
step "Running Python tests"
pytest -q -m "not slow"
